##**NUMPY BASICS**


#**CREATING A NUMPY ARRAY AND ITS ATTRIBUTES**

In [ ]:
#importing numpy library
import numpy as np
#creating a list
my_list = [1,2,3,4,5]
#changing the list into a numpy array
my_array = np.array(my_list)
#printing the 1-D numpy array
print(my_array)

#creating a 0-D numpy array
zero_array = np.array(42)
#printing the array
print(zero_array)

#Instead of creeating a list on a seperate variable we ban direct pass it to .array()function like this:
my_array = np.array([1,2,3,4,5])
#printing the 1-D numpy array
print(my_array)

#lets create a 2-D array!
two_d_array = np.array([[1,2,3],[4,5,6]])
#printing the 2-D array
print(two_d_array)

#lets create a 3-D array now!
three_d_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#printing the 3-D array
print(three_d_array)

[1 2 3 4 5]
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#lets create an array and see its attributes!
my_array = np.array([[1,2,3],[4,5,6]])
#printing the array
print(my_array) #printing the array
print(my_array.shape) #printing the shape of the array
print(my_array.ndim) #printing the demension of the array
print(my_array.dtype) #printning the type of the array
print(my_array.size) #printing the size of the array

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64
6


##**ACCESING AND MANIPULATIONG ARRAY ELEMENTS**

In [ ]:
#lets create a 1-D array and print one of its elements
one_arr = np.array([1,2,3,4,5,6])
print(one_arr[4])

#Lets print using  negative indexing
print(one_arr[-3])

5
4


In [ ]:
#Lets code for a 2-D array
two_arr = np.array([[1,2,3],[4,5,6]])
print(two_arr[0,2])

3


In [ ]:
#Lets move to a 3-D array
three_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_arr[1,1,2])

#negative indexing
three_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_arr[1,1,-2])



12
11


##**SLICING ARRAYS**

##**Some Important Slicing Concepts**
array[start:end]

array[start:end:steps]


In [ ]:
#slicing array form 0th index to 8th index
my_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array[0:8])#array[start:end]

[1 2 3 4 5 6 7 8]


In [ ]:
#Slicing with steps

my_new_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_new_array[0:9:2])#array[start:end:steps]

[1 3 5 7 9]


In [ ]:
#Slicing on a 2-D array
my_two_d = np.array([[1,2,3,4,5,6,7,8,9],[11,10,12,13,14,15,16,17,18]])
print(my_two_d[0,3:6])

[4 5 6]


##**HOMEWORK**

SLICING ON A 3-D ARRAY

In [60]:
#Slicing on a 3-D Array

import numpy as np

my_3d = np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[9,10,11,12],[13,14,15,16]]
])

# Slicing: Get second and third elements from row 0 in the first layer
print(my_3d[0, 0, 1:3])  # Output: [2 3]

# Slicing: Get first rows from both layers
print(my_3d[:, 0, :])  # Output: [[1 2 3 4], [9 10 11 12]]


[2 3]
[[ 1  2  3  4]
 [ 9 10 11 12]]


##**Class Work**


In [58]:
#1. Create a NumPy array from the list [7, 14, 21, 281]. Print the array.

import numpy as np
#creating a list
my_list = [1,2,3,4,5]
#changing the list into a numpy array
my_array = np.array(my_list)
print(my_array)


#2.Create a 2D NumPy array [[5, 10, 15], [20, 25, 30]]. Print its shape and number of dimensions using array. ndim.

import numpy as np

my_array = np.array([[5,10,15],[20,25,26]])
print(my_array.shape)
print(my_array.ndim)


#3.Use np. zeros to create a 2D array of shape (2, 3). Then, use np. arange to create an array from 0 to 12 with a step of 3. Print both arrays.

import numpy as np

# Create a 2D array of shape (2, 3) filled with zeros
array_zeros = np.zeros((2, 3))

# Create an array from 0 to 12 with a step of 3
array_arange = np.arange(0, 13, 3)

# Print both arrays
print("2D array of zeros (shape 2x3):")
print(array_zeros)

print("\nArray from 0 to 12 with step 3:")
print(array_arange)


#4.Create a NumPy array [2, 4, 6, 8]. Multiply all elements by 3 and print the result.

import numpy as np

     # Create the NumPy array
arr = np.array([2, 4, 6, 81])

     # Multiply all elements by 3
result = arr * 3

     # Print the result
print(result)


#5.Create a NumPy array [1, 3, 5, 7, 9, 11]. Print the third element and a slice from index 1 to 3 (inclusive).

import numpy as np

arr = np.array([1, 3, 5, 7, 9, 11])

     # Print the third element
print("Third element:", arr[2])

     # Print a slice from index 1 to 3 (inclusive)
print("Slice from index 1 to 3:", arr[1:3])






[1 2 3 4 5]
(2, 3)
2
2D array of zeros (shape 2x3):
[[0. 0. 0.]
 [0. 0. 0.]]

Array from 0 to 12 with step 3:
[ 0  3  6  9 12]
[  6  12  18 243]
Third element: 5
Slice from index 1 to 3: [3 5]
