#**Hands On Exercise practice:-Linear Algebra for AI**


**Exercise 1:-Working with Scaler and Vectors**

In [2]:
import numpy as np

scaler = 9
print(scaler)

vector = np.array([3,6,8,45,19])
print(vector)

scaled_vector = vector * scaler
print(scaled_vector)

#creating 2 vectors and doing addition and subtraction

import numpy as np

# Creating two vectors
vector1 = np.array([4, 7])
vector2 = np.array([1, 3])

# Vector Addition
addition = vector1 + vector2

# Vector Subtraction
subtraction = vector1 - vector2

# Displaying the results
# print("Vector 1:", vector1)
# print("Vector 2:", vector2)
print("Addition (vector1 + vector2):", addition)
print("Subtraction (vector1 - vector2):", subtraction)


9
[ 3  6  8 45 19]
[ 27  54  72 405 171]
Vector 1: [4 7]
Vector 2: [1 3]
Addition (vector1 + vector2): [ 5 10]
Subtraction (vector1 - vector2): [3 4]


#**MATRIX CREATION AND SIMPLE OPERATION**

In [6]:
matrix1 = np.array([[1, 2], [4, 5]])
matrix2 = np.array([[5, 6], [7, 8]])

add = matrix1+matrix2
print(add)

subtraction = matrix1 - matrix2
print(subtraction)

multiplication = matrix1 * matrix2
print(multiplication)

matmul = np.dot(matrix1,matrix2)
print(matmul)


[[ 6  8]
 [11 13]]
[[-4 -4]
 [-3 -3]]
[[ 5 12]
 [28 40]]
[[19 22]
 [55 64]]


###**Multiplication in manual**

In [11]:
import numpy as np

A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

index_A = A[0,0] * B[0,0] + A[0,1] * B[1,0]
index_B = A[0,0] * B[0,1] + A[0,1] * B[1,1]  # fixed here
index_C = A[1,0] * B[0,0] + A[1,1] * B[1,0]
index_D = A[1,0] * B[0,1] + A[1,1] * B[1,1]

print(index_A)  # 19
print(index_B)  # 22
print(index_C)  # 43
print(index_D)  # 50

matmal = np.dot(A, B)
print(matmal)


19
22
43
50
[[19 22]
 [43 50]]
